# Added for BrowserCMS (to test using test/dummy app)
ENV["RAILS_ENV"] ||= "test"
require 'simplecov'

require File.expand_path("../../../test/dummy/config/environment.rb", __FILE__)
ENV["RAILS_ROOT"] ||= File.dirname(__FILE__) + "../../../test/dummy"

require 'factory_bot'
# require 'factory_bot/step_definitions'
require File.join(File.dirname(__FILE__), '../../test/factories/factories')
require File.join(File.dirname(__FILE__), '../../test/factories/attachable_factories')
World(FactoryBot::Syntax::Methods)

require 'aruba/cucumber'

require 'capybara/dsl'
# poltergeist deleted: it drives PhantomJS, which was abandoned in 2018, and
# nothing here ever selected it. There are no @javascript scenarios and no
# Capybara driver is assigned anywhere, so the require and its two commented-out
# driver assignments were the whole of its presence. Phase 1, P1-7.

# Where aruba generates projects.
#
# This MUST sit outside the browsercms checkout, and the reason is specific:
# `rails new` does not run the `rails` on PATH. Rails::AppRailsLoader walks up
# from the working directory looking for `bin/rails` or `script/rails` and execs
# the first one it finds. From a working directory inside this repo it finds
# this engine's own script/rails, which loads test/dummy's app, and railties
# then refuses with
#
#   Can't initialize a new Rails application within the directory of another
#
# Every @cli scenario that generates a project dies there, and the rest die
# downstream on the directory that was never created.
#
# These are aruba *configuration*, not instance variables. Aruba 0.14 dropped
# the @aruba_dir/@dirs API this file used to set in a Before hook; the
# assignments were silently ignored and the working directory fell back to the
# default `tmp/aruba` -- inside the repo. @aruba_timeout_seconds was never an
# aruba variable under any version (the deprecated name was
# @aruba_exit_timeout), so the timeout has always been the 15s default too.
ARUBA_WORKING_DIR = "../browsercms-tmp/aruba"
ARUBA_SCRATCH_DIR = "../browsercms-tmp/cached-bcms-project"

Aruba.configure do |config|
  config.working_directory = ARUBA_WORKING_DIR

  # Generating a project runs `bundle install`, which is nowhere near the 15s
  # default on a cold cache.
  config.exit_timeout = 300
end

Before do
  # Run once per test run.
  if !$cleaned_cached_project
    FileUtils.rm_rf(ARUBA_SCRATCH_DIR)
    $cleaned_cached_project = true
  end
end

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'

# Capybara defaults to XPath selectors rather than Webrat's default of CSS3. In
# order to ease the transition to Capybara we set the default here. If you'd
# prefer to use XPath just remove this line and adjust any selectors in your
# steps to use the XPath syntax.
Capybara.default_selector = :css

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# Load the seed data once at the start of the test run.
# By doing this here, and using transaction strategy, we ensure the fastest possible tests.
DatabaseCleaner.clean_with :truncation
# Seeding is noisy and the output tells you nothing. This used to call
# Kernel#silence_stream, which Rails 4.2 deprecated and 5.0 removed outright --
# on the next bundle it raised NoMethodError right here and took the whole
# cucumber run down before a single scenario was collected.
#
# 5.0 keeps the implementation, but as a private instance method on
# ActiveSupport::Testing::Stream, a module meant to be mixed into test cases and
# one that does not exist at all on 4.2. So there is no name that resolves on
# both. It is six lines; define it locally and neither version matters.
def without_output_from(stream)
  original = stream.dup
  stream.reopen(IO::NULL)
  stream.sync = true
  yield
ensure
  stream.reopen(original)
  original.close
end

without_output_from(STDOUT) do
  require File.join(File.dirname(__FILE__), '../../db/seeds.rb')
end
