language: ruby
dist: bionic
os: linux

branches:
  only:
  - master
  - develop

addons:
  postgresql: 15
#   apt:
#       packages:
#         - postgresql-14

services:
  - postgresql

env:
  global:
    - PGHOST=localhost
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=''

cache:
  bundler: true

bundler_args: --without development

before_install:
  - pg_lsclusters

  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
  - sudo apt-get update
  - sudo apt install postgresql postgresql-client -y
  
  # fix the postgres port number so that it is the normal default
  # - sudo sed -i 's/port = 5432/port = 5433/' /etc/postgresql/13/main/postgresql.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/15/main/postgresql.conf
  # fix postgres authentication
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/15/main/pg_hba.conf
  # restart postgres to pickup the config changes
  # - sudo service postgresql restart
  # manually start new postgres versions in old distros
  - pg_lsclusters
  #- sudo mkdir -p /usr/local/pgsql/data
  #- sudo initdb -D /usr/local/pgsql/data
  - sudo -u postgres /usr/lib/postgresql/15/bin/pg_ctl restart -l /var/log/postgresql/postgresql-15-main.log -D /var/lib/postgresql/15/main
  # give it a bit of time to run
  - sleep 1
  # just check the version to make sure it is what we expect
  - pg_lsclusters

install:
  - echo pg pass:$PGPASSWORD
  - psql -c 'create database browsercms_test;' -U postgres
  - gem install bundler:1.17.3
  - bundle install

script: bundle exec rake
