language: ruby
dist: xenial
os: linux

branches:
  only:
  - master
  - develop

addons:
  postgresql: 14
  apt:
      packages:
        - postgresql-14

cache:
  bundler: true

bundler_args: --without development

before_install:
  - sudo apt-get update
  # fix the postgres port number so that it is the normal default
  # - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/15/main/postgresql.conf
  # restart postgres to pickup the config changes
  - sudo service postgresql restart
  # give it a bit of time to run
  - sleep 1
  # just check the version to make sure it is what we expect
  - postgres --version

install:
  - psql -c 'create database browsercms_test;' -U postgres
  - gem install bundler:1.17.3
  - bundle install

script: bundle exec rake
