language: ruby
dist: xenial
os: linux

branches:
  only:
  - master
  - develop

env:
  global:
   - PGUSER=postgres
   - PGPORT=5432
   - PGHOST=localhost

addons:
  postgresql: '13'
  apt:
      packages:
        - postgresql-13

cache:
  bundler: true

bundler_args: --without development

before_install:
  - pg_lsclusters
  - sudo cat /etc/postgresql/*/main/pg_hba.conf
  - sudo apt-get update
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - postgres --version

install:
  - psql -c 'create database browsercms_test;' -U postgres
  - gem install bundler:1.17.3
  - bundle install

script: bundle exec rake
